import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { hasPermission } from "../lib/platform";
import { advertisingMetrics, assertSameOrganization, canonicalProductKey, christianModel, dependencyEvent, jointAssessment, safeDemandEnvelope, scoreOutcome, validateChristianReport, vectorRecommendation, type AdvertisingSignal, type ChristianReportFact } from "../lib/vector";
import type { OracleAssessment } from "../lib/oracle";

const entity={sku:"SKU-1",asin:"B000TEST",marketplace:"US"};
function signal(metric:AdvertisingSignal["metric"],value:number):AdvertisingSignal{return{id:`${metric}-1`,organizationId:"org-a",entity,metric,value,unit:"count",periodStart:"2026-08-01T00:00:00.000Z",periodEnd:"2026-08-07T00:00:00.000Z",observedAt:"2026-08-07T00:00:00.000Z",source:"test",freshness:"current",confidence:.9,classification:"OBSERVATION",provenance:{}}}
const adSignals=[signal("spend",100),signal("ad_sales",500),signal("total_sales",1000),signal("impressions",10000),signal("clicks",100),signal("orders",20),signal("units",25)];

test("Vector derives independent efficiency without claiming causation",()=>{const m=advertisingMetrics(adSignals);assert.equal(m.acos,.2);assert.equal(m.tacos,.1);assert.equal(m.roas,5);assert.equal(m.cpc,1);assert.equal(m.ctr,.01);assert.equal(m.cvr,.2);const r=vectorRecommendation(adSignals);assert.equal(r.action,"HOLD");assert.equal(r.requiresJointDecision,true);assert.match(r.assumptions.join(" "),/does not establish/)});
test("Vector refuses a material recommendation when evidence is incomplete",()=>{const r=vectorRecommendation([signal("spend",100)]);assert.equal(r.action,"GATHER_MORE_EVIDENCE");assert.equal(r.status,"insufficient_evidence")});
test("Christian report ingestion is approved, idempotent, and target-specific",()=>{const fact:ChristianReportFact={sourceMessageId:"msg-1",sender:"ccachafeiro@teikametrics.com",receivedAt:"2026-08-01T00:00:00.000Z",subject:"Weekly Report Accutime x Teikametrics",entity,metric:"tacos_target",value:.12,unit:"ratio",classification:"OBSERVATION",provenance:{}};const a=validateChristianReport(fact),b=validateChristianReport(fact);assert.equal(a.idempotencyKey,b.idempotencyKey);assert.equal(christianModel([fact]).targetTacos,.12);assert.throws(()=>validateChristianReport({...fact,sender:"unknown@example.com"}))});
test("Christian model does not invent a universal TACoS rule",()=>{assert.match(christianModel([]).unsupportedAssumptions[0],/No universal TACoS threshold/)});
test("Safe Demand Envelope constrains advertising to supply",()=>{const e=safeDemandEnvelope({product:entity,currentWeeklyDemand:100,usableInventory:600,weeksUntilReplenishment:4,minimumBufferUnits:100});assert.equal(e.maximumSustainableWeeklyDemand,125);assert.equal(e.safeIncrementalUnits,25);assert.equal(e.safeAdvertisingAcceleration,.25)});
test("Safe Demand Envelope remains unavailable instead of inventing a replenishment horizon",()=>{assert.equal(safeDemandEnvelope({product:entity,currentWeeklyDemand:100,usableInventory:600}).status,"unavailable")});

const forecast=(model:"MichaelModel"|"OracleModel",weeklyRate:number)=>({model,modelVersion:"1",product:entity,horizonWeeks:8,baseForecast:weeklyRate*8,lowerBound:weeklyRate*7,upperBound:weeklyRate*9,weeklyRate,confidence:.8,assumptions:[],missingEvidence:[],drivers:[],calculatedAt:"2026-08-08T00:00:00.000Z"});
const oracle:OracleAssessment={organizationId:"org-a",status:"available",assessedAt:"2026-08-08T00:00:00.000Z",evidenceCount:10,limitations:[],decisions:[{product:entity,inventory:{product:entity,asOf:"2026-08-08T00:00:00.000Z",buckets:{amazonOnHand:600,amazonOnOrder:0,awcOnHand:0,dfAvailable:0,transferable:0,committed:0,promoCommitted:0,inbound:0,protected:0},usableInventory:600,currentWos:6,risk:"balanced",assumptions:[],missingEvidence:[]},comparison:{michael:forecast("MichaelModel",120),oracle:forecast("OracleModel",100),absoluteDifference:160,percentageDifference:.2,materiallyDisagrees:true,disagreementDrivers:["Orders diverge from observed sales."],valueOfInformation:{recommendation:"GATHER_EVIDENCE",score:.7,rationale:"Verify demand.",nextEvidence:["Cancellation evidence"]}},recommendedOption:{action:"HUMAN_REVIEW",quantity:0,expectedStockoutProbability:.1,expectedExcessInventory:0,expectedServiceLevel:.9,leadTimeDays:28,moqImpact:"none",risk:"medium",reversibility:"easy",confidence:.8,why:["Review"],whatCouldMakeItWrong:["Demand shift"]},alternatives:[]}]};
test("Joint engine constrains advertising and preserves possible futures",()=>{const a=jointAssessment("org-a",adSignals,oracle,"2026-08-08T00:00:00.000Z");assert.equal(a.decisions.length,1);assert.equal(a.decisions[0].safeDemandEnvelope.safeIncrementalUnits,0);assert.ok(a.decisions[0].options.some((o)=>o.kind==="CONTROLLED_EXPERIMENT"));assert.equal(a.decisions[0].disagreement.materiallyDisagrees,true);assert.ok(a.decisions[0].causalNeighborhood.every((e)=>e.status!=="EXPERIMENTAL"&&e.status!=="REPLICATED"))});
test("Inventory changes invalidate Vector and advertising changes invalidate Oracle",()=>{assert.equal(dependencyEvent({organizationId:"org-a",sourceDomain:"VECTOR",sourceId:"v",targetDomain:"ORACLE",targetId:"o",event:"ADVERTISING_CHANGED",occurredAt:"2026-08-08T00:00:00.000Z"}).invalidates,"FORECAST");assert.equal(dependencyEvent({organizationId:"org-a",sourceDomain:"ORACLE",sourceId:"o",targetDomain:"VECTOR",targetId:"v",event:"REPLENISHMENT_CHANGED",occurredAt:"2026-08-08T00:00:00.000Z"}).invalidates,"RECOMMENDATION")});
test("Entity resolution and organization isolation are explicit",()=>{assert.equal(canonicalProductKey(entity),"us:B000TEST");assert.throws(()=>assertSameOrganization({organizationId:"org-a"},{organizationId:"org-b"}))});
test("Outcome learning scores each model without fabricating unavailable metrics",()=>{const score=scoreOutcome({model:"JOINT",predicted:{spend:100,units:120,wos:6},actual:{spend:110,units:100,wos:5}});assert.equal(score.spendError,10);assert.equal(score.unitError,-20);assert.equal(score.complete,false)});
test("Vector and joint RBAC preserve approval authority",()=>{assert.equal(hasPermission({role:"analyst"},"vector.plan"),true);assert.equal(hasPermission({role:"analyst"},"joint.approve"),false);assert.equal(hasPermission({role:"manager"},"joint.approve"),true);assert.equal(hasPermission({role:"viewer"},"vector.read"),true)});
test("migration 011 is additive, tenant scoped, indexed, idempotent, and immutable",async()=>{const sql=await readFile("db/migrations/011_vector_joint_decision_engine.sql","utf8");assert.match(sql,/organization_id text not null references platform_organizations/);assert.match(sql,/unique \(organization_id, source_message_id, fact_hash\)/);assert.match(sql,/joint_dependency_target_idx/);assert.match(sql,/joint_outcomes_immutable/);assert.doesNotMatch(sql,/drop table|truncate table|alter table .* drop column/i)});
