import type { OracleAssessment, OracleProductRef } from "../oracle";
import type { AdvertisingMetrics, AdvertisingSignal, ChristianAdvertisingModel, ChristianReportFact, DependencyEvent, Disagreement, JointAssessment, JointCausalEdge, JointOption, JointOutcome, ModelOutcomeScore, SafeDemandEnvelope, VectorRecommendation } from "./types";

function ratio(a?: number, b?: number) { return a === undefined || b === undefined || b === 0 ? undefined : a / b; }
function sum(signals: AdvertisingSignal[], metric: AdvertisingSignal["metric"]) { const values = signals.filter((s) => s.metric === metric).map((s) => s.value); return values.length ? values.reduce((a, b) => a + b, 0) : undefined; }
export function advertisingMetrics(signals: AdvertisingSignal[]): AdvertisingMetrics {
  const spend = sum(signals, "spend"), adSales = sum(signals, "ad_sales"), totalSales = sum(signals, "total_sales"), impressions = sum(signals, "impressions"), clicks = sum(signals, "clicks"), orders = sum(signals, "orders"), units = sum(signals, "units");
  return { spend, adSales, totalSales, impressions, clicks, orders, units, acos: ratio(spend, adSales), tacos: ratio(spend, totalSales), roas: ratio(adSales, spend), cpc: ratio(spend, clicks), ctr: ratio(clicks, impressions), cvr: ratio(orders, clicks) };
}
export function christianModel(facts: ChristianReportFact[], version = "1.0"): ChristianAdvertisingModel {
  const target = facts.find((f) => f.metric === "tacos_target")?.value;
  const action = [...facts].reverse().find((f) => f.actionProposed)?.actionProposed;
  return { name: "Christian Advertising Model", version, reportSource: "Approved Teikametrics report evidence", effectiveAt: facts.at(-1)?.receivedAt ?? new Date(0).toISOString(), targetTacos: target, observations: {}, recommendation: action, rationale: facts.flatMap((f) => f.rationale ? [f.rationale] : []), unsupportedAssumptions: target === undefined ? ["No universal TACoS threshold is inferred; an explicit target is required."] : [] };
}
export function vectorRecommendation(signals: AdvertisingSignal[]): VectorRecommendation {
  const currentState = advertisingMetrics(signals); const scope = signals[0]?.entity ?? { sku: "unresolved" };
  const complete = currentState.spend !== undefined && currentState.adSales !== undefined && currentState.clicks !== undefined && currentState.impressions !== undefined;
  if (!complete) return { action: "GATHER_MORE_EVIDENCE", scope, currentState, confidence: 0, evidence: signals.map((s) => s.id), assumptions: [], downside: ["A material advertising change cannot be evaluated without spend, attributed sales, clicks, and impressions."], reversibility: "easy", observationWindowDays: 7, requiresJointDecision: false, status: "insufficient_evidence" };
  return { action: "HOLD", scope, currentState, confidence: Math.min(...signals.map((s) => s.confidence)), evidence: signals.map((s) => s.id), assumptions: ["Observed attribution does not establish incremental causation.", "Inventory compatibility must be checked before demand acceleration."], downside: ["Holding may forgo profitable demand; margin and incrementality evidence are unavailable."], reversibility: "easy", observationWindowDays: 7, requiresJointDecision: true, status: "ready" };
}
export function safeDemandEnvelope(input: { product: OracleProductRef; currentWeeklyDemand?: number; usableInventory?: number; weeksUntilReplenishment?: number; minimumBufferUnits?: number }): SafeDemandEnvelope {
  const { currentWeeklyDemand, usableInventory, weeksUntilReplenishment, minimumBufferUnits = 0 } = input;
  if (currentWeeklyDemand === undefined || usableInventory === undefined || !weeksUntilReplenishment || weeksUntilReplenishment <= 0) return { product: input.product, currentWeeklyDemand, minimumBufferUnits, weeksUntilReplenishment, status: "unavailable", constraints: ["Demand, usable inventory, and a positive replenishment horizon are required."], assumptions: [] };
  const maximumSustainableWeeklyDemand = Math.max(0, (usableInventory - minimumBufferUnits) / weeksUntilReplenishment);
  const safeIncrementalUnits = Math.max(0, maximumSustainableWeeklyDemand - currentWeeklyDemand);
  return { product: input.product, currentWeeklyDemand, maximumSustainableWeeklyDemand, safeIncrementalUnits, safeAdvertisingAcceleration: currentWeeklyDemand > 0 ? safeIncrementalUnits / currentWeeklyDemand : undefined, minimumBufferUnits, weeksUntilReplenishment, status: "available", constraints: ["Usable inventory buckets remain separated according to Oracle rules."], assumptions: ["Demand is held constant through the replenishment horizon."] };
}
export function dependencyEvent(input: Omit<DependencyEvent, "invalidates">): DependencyEvent { return { ...input, invalidates: input.sourceDomain === "VECTOR" ? "FORECAST" : "RECOMMENDATION" }; }
export function causalNeighborhood(): JointCausalEdge[] { return [["Bid","CPC","ASSUMED"],["CPC","Traffic","INFERRED"],["Traffic","PDP sessions","INFERRED"],["PDP sessions","Conversion","INFERRED"],["Conversion","Units","OBSERVED"],["Units","Inventory depletion","OBSERVED"],["Inventory depletion","WOS","INFERRED"],["WOS","Availability risk","INFERRED"],["Availability","Conversion","ASSUMED"],["Units","Revenue","OBSERVED"],["Advertising spend","Demand generation","ASSUMED"]].map(([from,to,status]) => ({ from, to, status: status as JointCausalEdge["status"], evidenceIds: [], explanation: `${from} to ${to} remains ${String(status).toLowerCase()} until stronger evidence is linked.` })); }
function options(envelope: SafeDemandEnvelope, vector: VectorRecommendation, currentWos?: number): JointOption[] {
  const base: JointOption[] = [{ kind: "DO_NOTHING", expectedUnits: envelope.currentWeeklyDemand, expectedWos: currentWos, confidence: vector.confidence, uncertainty: 1-vector.confidence, reversibility: "easy", reasons: ["Preserves the current demand and inventory trajectory."], constraintsSatisfied: true, recommended: false }];
  if (envelope.status === "available" && (envelope.safeIncrementalUnits ?? 0) > 0) base.push({ kind: "ADJUST_ADVERTISING", expectedUnits: envelope.maximumSustainableWeeklyDemand, expectedWos: currentWos, confidence: vector.confidence, uncertainty: 1-vector.confidence, reversibility: "easy", reasons: [`Advertising may create up to ${envelope.safeIncrementalUnits?.toFixed(1)} incremental weekly units inside the current supply constraint.`], constraintsSatisfied: true, recommended: false });
  else base.push({ kind: "CONTROLLED_EXPERIMENT", expectedUnits: envelope.currentWeeklyDemand, expectedWos: currentWos, confidence: Math.min(vector.confidence, .5), uncertainty: Math.max(1-vector.confidence, .5), reversibility: "easy", reasons: ["The safe demand envelope is unavailable or constrained; reduce uncertainty before changing demand."], constraintsSatisfied: true, recommended: false });
  const winner = base.find((o) => o.kind === "ADJUST_ADVERTISING") ?? base.find((o) => o.kind === "CONTROLLED_EXPERIMENT") ?? base[0]; winner.recommended = true; return base;
}
export function jointAssessment(organizationId: string, vectorSignals: AdvertisingSignal[], oracle: OracleAssessment, asOf = new Date().toISOString()): JointAssessment {
  const groups = new Map<string, AdvertisingSignal[]>(); for (const signal of vectorSignals) { const key = `${signal.entity.marketplace ?? ""}:${signal.entity.sku}`; groups.set(key, [...(groups.get(key) ?? []), signal]); }
  const vectorRecommendations = [...groups.values()].map(vectorRecommendation); const decisions: JointAssessment["decisions"] = [];
  for (const vector of vectorRecommendations) { const od = oracle.decisions.find((d) => d.product.sku === vector.scope.sku && (d.product.marketplace ?? "") === (vector.scope.marketplace ?? "")); if (!od) continue; const weekly = od.comparison.oracle.weeklyRate || undefined; const leadDays = od.recommendedOption.leadTimeDays; const envelope = safeDemandEnvelope({ product: od.product, currentWeeklyDemand: weekly, usableInventory: od.inventory.usableInventory, weeksUntilReplenishment: leadDays ? leadDays/7 : undefined, minimumBufferUnits: weekly ? weekly*2 : 0 }); const disagreement: Disagreement = { materiallyDisagrees: od.comparison.materiallyDisagrees || vector.status === "insufficient_evidence", perspectives: [{model:"MICHAEL",position:`${od.comparison.michael.weeklyRate.toFixed(1)} units/week`,confidence:od.comparison.michael.confidence},{model:"ORACLE",position:`${od.comparison.oracle.weeklyRate.toFixed(1)} units/week`,confidence:od.comparison.oracle.confidence},{model:"VECTOR",position:vector.action,confidence:vector.confidence}], differingAssumptions: [...od.comparison.disagreementDrivers, ...vector.assumptions], evidenceToResolve: od.comparison.valueOfInformation.nextEvidence }; const intervention = weekly !== undefined && vector.expectedIncrementalUnits !== undefined ? weekly + vector.expectedIncrementalUnits : undefined; decisions.push({ product: od.product, vector, safeDemandEnvelope: envelope, baselineWeeklyDemand: weekly, interventionWeeklyDemand: intervention, options: options(envelope, vector, od.inventory.currentWos), disagreement, causalNeighborhood: causalNeighborhood() }); }
  return { organizationId, status: decisions.length ? (vectorSignals.some((s) => s.freshness === "stale") ? "partial" : "available") : "unavailable", assessedAt: asOf, vectorRecommendations, oracleAssessment: oracle, decisions, evidenceCount: vectorSignals.length + oracle.evidenceCount, limitations: decisions.length ? ["Joint recommendations use only organization-scoped normalized evidence and preserve unknown economics as unavailable."] : ["No advertising product could be joined to an Oracle inventory assessment. No sample joint decision was generated."] };
}
export function scoreOutcome(outcome: JointOutcome): ModelOutcomeScore { const diff = (a?:number,b?:number) => a === undefined || b === undefined ? undefined : b-a; const spendError=diff(outcome.predicted.spend,outcome.actual.spend),unitError=diff(outcome.predicted.units,outcome.actual.units),wosError=diff(outcome.predicted.wos,outcome.actual.wos),contributionError=diff(outcome.predicted.contribution,outcome.actual.contribution); return { model: outcome.model, spendError, unitError, wosError, contributionError, complete: [spendError,unitError,wosError,contributionError].every((v)=>v!==undefined) }; }
