import type { EvidenceFreshness } from "../evidence";
import type { OracleAssessment, OracleProductRef } from "../oracle";

export type VectorClassification = "OBSERVATION" | "ASSUMPTION" | "HYPOTHESIS" | "INTERVENTION" | "PREDICTION" | "OUTCOME";
export type VectorMetric = "spend" | "ad_sales" | "total_sales" | "impressions" | "clicks" | "orders" | "units" | "bid" | "budget" | "margin" | "tacos_target";
export type VectorAction = "INCREASE_BID" | "DECREASE_BID" | "INCREASE_BUDGET" | "DECREASE_BUDGET" | "PAUSE" | "ENABLE" | "REALLOCATE" | "EXPAND_TARGETING" | "REDUCE_TARGETING" | "HOLD" | "TEST" | "GATHER_MORE_EVIDENCE";

export type AdvertisingEntity = OracleProductRef & { campaignId?: string; adGroupId?: string; targetId?: string; keyword?: string; searchTerm?: string; brand?: string };
export type AdvertisingSignal = { id: string; organizationId: string; entity: AdvertisingEntity; metric: VectorMetric; value: number; unit: string; periodStart: string; periodEnd: string; observedAt: string; source: string; freshness: EvidenceFreshness; confidence: number; classification: VectorClassification; provenance: Record<string, unknown> };
export type AdvertisingMetrics = { spend?: number; adSales?: number; totalSales?: number; impressions?: number; clicks?: number; orders?: number; units?: number; acos?: number; tacos?: number; roas?: number; cpc?: number; ctr?: number; cvr?: number };
export type VectorRecommendation = { action: VectorAction; scope: AdvertisingEntity; currentState: AdvertisingMetrics; proposedChange?: number; expectedIncrementalUnits?: number; expectedEconomicImpact?: { amount: number; currency: string }; confidence: number; evidence: string[]; assumptions: string[]; downside: string[]; reversibility: "easy" | "moderate" | "difficult"; observationWindowDays: number; requiresJointDecision: boolean; status: "ready" | "insufficient_evidence" };

export type ChristianReportFact = { sourceMessageId: string; sender: string; receivedAt: string; subject: string; entity: AdvertisingEntity; metric?: VectorMetric; value?: number; unit?: string; actionProposed?: VectorAction; actionExecuted?: boolean; rationale?: string; expectedResult?: string; actualResult?: string; classification: VectorClassification; provenance: Record<string, unknown> };
export type ChristianAdvertisingModel = { name: "Christian Advertising Model"; version: string; reportSource: string; effectiveAt: string; targetTacos?: number; observations: AdvertisingMetrics; recommendation?: VectorAction; rationale: string[]; unsupportedAssumptions: string[] };

export type EdgeEpistemicStatus = "OBSERVED" | "ASSUMED" | "INFERRED" | "QUASI_CAUSAL" | "EXPERIMENTAL" | "REPLICATED";
export type JointCausalEdge = { from: string; to: string; status: EdgeEpistemicStatus; evidenceIds: string[]; explanation: string };
export type SafeDemandEnvelope = { product: OracleProductRef; currentWeeklyDemand?: number; maximumSustainableWeeklyDemand?: number; safeIncrementalUnits?: number; safeAdvertisingAcceleration?: number; minimumBufferUnits?: number; weeksUntilReplenishment?: number; status: "available" | "unavailable"; constraints: string[]; assumptions: string[] };
export type JointOptionKind = "DO_NOTHING" | "ADJUST_ADVERTISING" | "TRANSFER_INVENTORY" | "TRANSFER_AND_ADVERTISE" | "REPLENISH_AND_HOLD" | "REDUCE_UNTIL_REPLENISHMENT" | "CONTROLLED_EXPERIMENT";
export type JointOption = { kind: JointOptionKind; expectedSales?: number; expectedUnits?: number; expectedAdSpend?: number; expectedTacos?: number; expectedWos?: number; stockoutProbability?: number; excessInventoryProbability?: number; expectedContribution?: number; confidence: number; uncertainty: number; reversibility: "easy" | "moderate" | "difficult"; reasons: string[]; constraintsSatisfied: boolean; recommended: boolean };
export type Disagreement = { materiallyDisagrees: boolean; perspectives: Array<{ model: "MICHAEL" | "CHRISTIAN" | "ORACLE" | "VECTOR" | "JOINT"; position: string; confidence?: number }>; differingAssumptions: string[]; evidenceToResolve: string[] };
export type JointAssessment = { organizationId: string; status: "available" | "partial" | "unavailable"; assessedAt: string; vectorRecommendations: VectorRecommendation[]; oracleAssessment: OracleAssessment; decisions: Array<{ product: OracleProductRef; vector: VectorRecommendation; safeDemandEnvelope: SafeDemandEnvelope; baselineWeeklyDemand?: number; interventionWeeklyDemand?: number; options: JointOption[]; disagreement: Disagreement; causalNeighborhood: JointCausalEdge[] }>; evidenceCount: number; limitations: string[] };
export type DependencyEvent = { organizationId: string; sourceDomain: "VECTOR" | "ORACLE"; sourceId: string; targetDomain: "VECTOR" | "ORACLE"; targetId: string; event: "ADVERTISING_CHANGED" | "REPLENISHMENT_CHANGED" | "INVENTORY_CHANGED" | "DEMAND_CHANGED"; invalidates: "FORECAST" | "RECOMMENDATION"; occurredAt: string };
export type JointOutcome = { predicted: { spend?: number; units?: number; wos?: number; contribution?: number }; actual: { spend?: number; units?: number; wos?: number; contribution?: number }; model: "CHRISTIAN" | "MICHAEL" | "VECTOR" | "ORACLE" | "JOINT" };
export type ModelOutcomeScore = { model: JointOutcome["model"]; spendError?: number; unitError?: number; wosError?: number; contributionError?: number; complete: boolean };
